spring.application.name=jwtsecurity
server.port=8070
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/jwtsecurity
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.datasource.username=postgres
spring.datasource.password=1292003
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.error.include-message=always
spring.jpa.properties.hibernate.format_sql=true
spring.security.user.name=user
spring.security.user.password=user